parameters:
    jwt_expiration_in_seconds: 7200
    jwt_private_key_path: '%kernel.project_dir%/config/packages/%kernel.environment%/jwt/private.key'
    jwt_public_key_path: '%kernel.project_dir%/config/packages/%kernel.environment%/jwt/public.key'
    portal_url: '%env(PORTAL_URL)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller/'
        public: true
