services:

  frontend-react:
    container_name: frontend-react
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  backend-php:
    container_name: backend-php
    build: 
      context: ./backend
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    volumes:
      - ./backend:/srv/backend

  backend-nginx:
    container_name: backend-nginx
    image: nginx:alpine
    volumes:
      - ./backend:/srv/backend
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend-php

  backend-database:
    container_name: backend-database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      PGPORT: 5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  database_data: